// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function LoadConfig():Promise<config.Configuration>;

export function SaveBuildingPositionsJSON(arg1:Record<string, any>):Promise<void>;

export function Screenshot():Promise<string>;

export function SetConfig(arg1:config.Configuration):Promise<void>;

export function TapBuilding(arg1:number,arg2:number):Promise<void>;
