// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}
