// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddDevice(arg1:string,arg2:string,arg3:string):Promise<Array<main.Device>>;

export function DeleteDevice(arg1:string):Promise<Array<main.Device>>;

export function GetDevices():Promise<Array<main.Device>>;

export function LoadConfig():Promise<config.Configuration>;
