// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveBuildingPositionsJSON(arg1) {
  return window['go']['main']['App']['SaveBuildingPositionsJSON'](arg1);
}

export function Screenshot() {
  return window['go']['main']['App']['Screenshot']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function TapBuilding(arg1, arg2) {
  return window['go']['main']['App']['TapBuilding'](arg1, arg2);
}
