package filepath

type Rect struct {
	X1, Y1, X2, Y2 int
}

type ImageProps struct {
	Path       string
	Resolution [2]int
	CropRect   Rect
	Threshold  float64
	Timeout    int
	Tag        string
}

var StrImagePosition = map[string]Rect{
	"WINDOWS_TITLE": {305, 68, 975, 100},
}

var FilePaths = map[string]string{
	"TEST_SRC_FOLDER_PATH":      "test_screen_caps\\",
	"TEST_CURR_SCREEN_CAP_PATH": "test_screen_caps\\current_cap.png",
	"ADB_EXE_PATH":              "adb\\adb.exe",
	"TESSERACT_EXE_PATH":        "tesseract\\tesseract.exe",
	"TESSDATA_CHI_SIM_PATH":     "tessdata\\chi_sim.traineddata",
	"SAVE_FOLDER_PATH":          "save\\",
}

var BuffsImageAndProps = map[string]ImageProps{
	"ENHANCED_GATHER_BLUE": {
		Path:       "resource\\buffs\\enhanced_gathering_blue.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        BOOSTS,
	},
	"ENHANCED_GATHER_PURPLE": {
		Path:       "resource\\buffs\\enhanced_gathering_purple.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        BOOSTS,
	},
}

// Continue similarly for:
var ItemsImageAndProps = map[string]ImageProps{
	"ENHANCED_GATHER_BLUE": {
		Path:       "resource\\items\\enhanced_gathering_blue.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        BOOSTS,
	},
	"ENHANCED_GATHER_PURPLE": {
		Path:       "resource\\items\\enhanced_gathering_blue.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        BOOSTS,
	},
}

var ImagePathAndProps = map[string]ImageProps{
	"MAP_BUTTON": {
		Path:       "resource\\map_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{10, 602, 113, 709},
		Threshold:  0.98,
		Timeout:    25,
		Tag:        MAP,
	},
	"HOME_BUTTON": {
		Path:       "resource\\home_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{10, 602, 113, 709},
		Threshold:  0.98,
		Timeout:    25,
		Tag:        MAP,
	},
	"GREEN_HOME_BUTTON": {
		Path:       "resource\\green_home_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        GREEN_HOME,
	},
	"WINDOW": {
		Path:       "resource\\window.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{1065, 56, 1128, 112},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        WINDOW,
	},
	"WINDOW_TITLE_MARK": {
		Path:       "resource\\window_title_mark.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{1065, 56, 1128, 112},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        WINDOW_TITLE,
	},
	"BUILDING_TITLE_MARK": {
		Path:       "resource\\building_title_left.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        BUILDING_TITLE,
	},
	"BUILDING_INFO_BUTTON": {
		Path:       "resource\\building_info_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        BUILDING_INFO,
	},
	"MENU_OPENED_IMAGE": {
		Path:       "resource\\menu_opened.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MENU_OPENED_IMAGE,
	},
	"MENU_BUTTON_IMAGE": {
		Path:       "resource\\menu_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{1204, 646, 1257, 693},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MENU_IMAGE,
	},
	"QUEST_CLAIM_BUTTON": {
		Path:       "resource\\quests_claim_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        CLAIM_BUTTON,
	},
	"BARRACKS_BUTTON": {
		Path:       "resource\\barracks_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        BARRACKS_BUTTON,
	},
	"ARCHER_RANGE_BUTTON": {
		Path:       "resource\\archery_range_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        ARCHER_RANGE_BUTTON,
	},
	"STABLE_BUTTON": {
		Path:       "resource\\stable_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        STABLE_BUTTON,
	},
	"SIEGE_WORKSHOP_BUTTON": {
		Path:       "resource\\siege_workshop_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        SIEGE_WORKSHOP_BUTTON,
	},
	"TRAINING_UPGRADE_BUTTON": {
		Path:       "resource\\training_upgrade_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TRAINING_UPGRADE_BUTTON,
	},
	"TRAIN_BUTTON": {
		Path:       "resource\\train_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TRAIN_BUTTON,
	},
	"UPGRADE_BUTTON": {
		Path:       "resource\\upgrade_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        UPGRADE_BUTTON,
	},
	"SPEED_UP_BUTTON": {
		Path:       "resource\\speed_up_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        SPEED_UP,
	},
	"DECREASING_BUTTON": {
		Path:       "resource\\decreasing_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        DECREASING,
	},
	"INCREASING_BUTTON": {
		Path:       "resource\\increasing_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        INCREASING,
	},
	"LOCK_BUTTON": {
		Path:       "resource\\lock_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        LOCK,
	},
	"RESOURCE_SEARCH_BUTTON": {
		Path:       "resource\\resource_search_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        RESOURCE_SEARCH,
	},
	"RESOURCE_GATHER_BUTTON": {
		Path:       "resource\\resource_gather_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        RESOURCE_GATHER,
	},
	"NEW_TROOPS_BUTTON": {
		Path:       "resource\\new_troops_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        NEW_TROOPS,
	},
	"TROOPS_MATCH_BUTTON": {
		Path:       "resource\\troops_match_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TROOPS_MATCH,
	},
	"VERIFICATION_CHEST_BUTTON": {
		Path:       "resource\\verification_chest_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VERIFICATION_CHEST,
	},
	"VERIFICATION_VERIFY_BUTTON": {
		Path:       "resource\\verification_verify_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VERIFICATION_VERIFY,
	},
	"VERIFICATION_CLOSE_REFRESH_OK_BUTTON": {
		Path:       "resource\\verification_close_refresh_ok_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VERIFICATION_CLOSE_REFRESH_OK,
	},
	"GIFTS_CLAIM_BUTTON": {
		Path:       "resource\\alliance_gifts_claim_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        GIFTS_CLAIM,
	},
	"TECH_RECOMMEND_IMAGE": {
		Path:       "resource\\alliance_tech_recommend.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TECH_RECOMMEND,
	},
	"TECH_DONATE_BUTTON": {
		Path:       "resource\\alliance_tech_donate.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TECH_DONATE,
	},
	"MATERIALS_PRODUCTION_BUTTON": {
		Path:       "resource\\materials_production_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MATERIALS_PRODUCTION,
	},
	"TAVERN_BUTTON": {
		Path:       "resource\\tavern_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        TAVERN_BUTTON,
	},
	"CHEST_OPEN_BUTTON": {
		Path:       "resource\\chest_open_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        CHEST_OPEN,
	},
	"CHEST_CONFIRM_BUTTON": {
		Path:       "resource\\chest_confirm_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        CHEST_CONFIRM,
	},
	"ATTACK_BUTTON_POS": {
		Path:       "resource\\attack_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        ATTACK_BUTTON,
	},
	"HOLD_POS_CHECKED": {
		Path:       "resource\\hold_posistion_checked.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        HOLD_POS_CHECKED,
	},
	"HOLD_POS_UNCHECK": {
		Path:       "resource\\hold_position_unchecked.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        HOLD_POS_UNCHECK,
	},
	"UNSELECT_BLUE_ONE_SAVE_BUTTON": {
		Path:       "resource\\unselect_save_blue_one.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.95,
		Timeout:    25,
		Tag:        UNSELECT_BLUE_ONE,
	},
	"SELECTED_BLUE_ONE_SAVE_BUTTON": {
		Path:       "resource\\selected_save_blue_one.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.95,
		Timeout:    25,
		Tag:        SELECTED_BLUE_ONE,
	},
	"SAVE_SWITCH_BUTTON": {
		Path:       "resource\\switch_save.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        SAVE_SWITCH,
	},
	"VICTORY_MAIL": {
		Path:       "resource\\victory_mail.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VICTORY_MAIL,
	},
	"DEFEAT_MAIL": {
		Path:       "resource\\defeat_mail.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        DEFEAT_MAIL,
	},
	"RETURN_BUTTON": {
		Path:       "resource\\return_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        RETURN_BUTTON,
	},
	"HOLD_ICON": {
		Path:       "resource\\hold_icon.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        HOLD_ICON,
	},
	"HOLD_ICON_SMALL": {
		Path:       "resource\\hold_icon_small.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        HOLD_ICON_SMALL,
	},
	"MARCH_BAR": {
		Path:       "resource\\march_bar.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MARCH_BAR,
	},
	"HEAL_ICON": {
		Path:       "resource\\heal_icon.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        HEAL_ICON,
	},
	"DAILY_AP_CLAIM_BUTTON": {
		Path:       "resource\\daily_ap_claim.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        DAILY_AP_CLAIM,
	},
	"USE_AP_BUTTON": {
		Path:       "resource\\use_ap.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        USE_AP,
	},
	"SCOUT_BUTTON": {
		Path:       "resource\\scout_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        SCOUT_BUTTON,
	},
	"SCOUT_EXPLORE_BUTTON": {
		Path:       "resource\\explore_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        EXPLORE_BUTTON,
	},
	"SCOUT_EXPLORE2_BUTTON": {
		Path:       "resource\\explore_button2.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        EXPLORE_BUTTON2,
	},
	"SCOUT_SEND_BUTTON": {
		Path:       "resource\\scout_send_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        SEND_BUTTON,
	},
	"MAIL_EXPLORATION_REPORT": {
		Path:       "resource\\mail_exploration_report.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MAIL_EXPLORATION_REPORT,
	},
	"MAIL_SCOUT_BUTTON": {
		Path:       "resource\\mail_scout_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        MAIL_SCOUT_BUTTON,
	},
	"INVESTIGATE_BUTTON": {
		Path:       "resource\\investigate_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        INVESTIGATE_BUTTON,
	},
	"GREAT_BUTTON": {
		Path:       "resource\\great_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        GREAT_BUTTON,
	},
	"SCOUT_IDLE_ICON": {
		Path:       "resource\\scout_idle_icon.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        IDLE_ICON,
	},
	"SCOUT_ZZ_ICON": {
		Path:       "resource\\scout_zz_icon.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        ZZ_ICON,
	},
	"MERCHANT_ICON": {
		Path:       "resource\\merchant_icon.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        MERCHANT_ICON,
	},
	"MERCHANT_FREE_BTN": {
		Path:       "resource\\merchant_free_btn.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        MERCHANT_FREE_BTN,
	},
	"MERCHANT_BUY_WITH_WOOD": {
		Path:       "resource\\merchant_buy_with_wood.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        MERCHANT_BUY_WITH_WOOD,
	},
	"MERCHANT_BUY_WITH_FOOD": {
		Path:       "resource\\merchant_buy_with_food.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        MERCHANT_BUY_WITH_FOOD,
	},
	"HAS_MATCH_QUERY": {
		Path:       "resource\\has_match_query.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.80,
		Timeout:    25,
		Tag:        HAS_MATCH_QUERY,
	},
	"VERIFICATION_VERIFY_TITLE": {
		Path:       "resource\\verification_verify_title.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VERIFICATION_VERIFY_TITLE,
	},
}

var GuiCheckImagePathAndProps = map[string]ImageProps{
	"VERIFICATION_VERIFY_BUTTON_IMAGE_PATH": {
		Path:       "resource\\verification_verify_button.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.90,
		Timeout:    25,
		Tag:        VERIFICATION_VERIFY,
	},
	"MAP_BUTTON_IMG_PATH": {
		Path:       "resource\\map_button_0.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{10, 602, 113, 709},
		Threshold:  0.98,
		Timeout:    25,
		Tag:        HOME,
	},
	"HOME_BUTTON_IMG_PATH": {
		Path:       "resource\\home_button_0.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{10, 602, 113, 709},
		Threshold:  0.98,
		Timeout:    25,
		Tag:        MAP,
	},
	"WINDOW_IMG_PATH": {
		Path:       "resource\\window.png",
		Resolution: [2]int{1280, 720},
		CropRect:   Rect{0, 0, 0, 0},
		Threshold:  0.70,
		Timeout:    25,
		Tag:        WINDOW,
	},
}

var GuiCheckImagePathAndPropsOrdered = []ImageProps{
	GuiCheckImagePathAndProps["VERIFICATION_VERIFY_BUTTON_IMAGE_PATH"],
	GuiCheckImagePathAndProps["MAP_BUTTON_IMG_PATH"],
	GuiCheckImagePathAndProps["HOME_BUTTON_IMG_PATH"],
	GuiCheckImagePathAndProps["WINDOW_IMG_PATH"],
}
